version: '2' # required to adjust maintainability checks
checks:
  method-lines:
    config:
      threshold: 100
  similar-code:
    config:
      threshold: 150
  identical-code:
    config:
      threshold: 150
