version: '2' # required to adjust maintainability checks
checks:
  method-lines:
    config:
      treshold: 100
  similar-code:
    config:
      threshold: 200
  identical-code:
    config:
      threshold: 200
